// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_well_known_nostr_json from "./routes/.well-known/nostr.json.ts";
import * as $_slug_ from "./routes/[slug].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $about from "./routes/about.tsx";
import * as $blog from "./routes/blog.tsx";
import * as $index from "./routes/index.tsx";
import * as $InfiniteCanvasIsland from "./islands/InfiniteCanvasIsland.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/.well-known/nostr.json.ts": $_well_known_nostr_json,
    "./routes/[slug].tsx": $_slug_,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/about.tsx": $about,
    "./routes/blog.tsx": $blog,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/InfiniteCanvasIsland.tsx": $InfiniteCanvasIsland,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
